### ISSUE TITLE
Local Client Stuck at 0% starting on Windows

### ISSUE THREAD

**Issue by mike240se** [OpenZWave/ozw-admin#49]
0.163 build, have a aeotec zstick plugged into windows.  Start local w/ com port selected sits at starting 0% forever.

Also, maybe related, in the config it defaults config and user value to c:/ if you try to change to any other path and save it crashes the entire program.  (perhaps windows wont let it write to c:\ and since we cant change it that is why it doesnt start? I tried run as admin too)

also just tried 0.169, same issue.

SS: https://i.imgur.com/lDTFitQ.png

EDIT: on 0.169 it does not crash when trying to save config path and user path, however it always reverts back to c:/

**Comment by Fishwaldo** [comment]
Most likely you specified the wrong/non-existent serial port. Please try 0.1.72 and make sure you select the right serial port.

**Comment by kpine** [comment]
I had the same problem in 0.1.69. I was specifying `COM3`. I'm now trying 0.1.72. Instead of a text field it produces a drop down menu with a selection of `\\.\COM3` instead, so I suppose there was some weird difference there. So that port works, it starts the network and discovers the nodes, however it eventually crashes during startup at various times, but it's 100% of the time. I'm not sure how to produce any kind of debugging log for Windows builds. The only thing I'm aware of is an application log in the Event Viewer.

```
Faulting application name: ozwadmin.exe, version: 0.1.72.0, time stamp: 0x5ef0f93f
Faulting module name: Qt5Core.dll, version: 5.12.8.0, time stamp: 0x5e82d0d9
Exception code: 0xc0000005
Fault offset: 0x00047f6d
Faulting process id: 0x1590
Faulting application start time: 0x01d648dcdf336cf3
Faulting application path: C:\Program Files (x86)\OpenZwave Admin\ozwadmin.exe
Faulting module path: C:\Program Files (x86)\OpenZwave Admin\Qt5Core.dll
Report Id: 2f79e3a5-ccc3-4b02-ae89-c387a0c10f32
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by mike240se** [comment]
I was definitely using the correct COM port but i was specifying as COM5 not \\.\COM5 so maybe that was the issue?

**Comment by Fishwaldo** [comment]
Honestly - I very rarely use Windows... so I'm going to say "yes" the format of the COM port was the issue. The drop down list should fix that moving forward though. 

Closing this.
